name: ${artifactId}
version: ${version}
main: ${plugin.mainClass}
description: Team Authenticator designed for The Overcast Network (oc.tc)

commands:
    setteam:
        usage: /setteam <team>
        description: Authenticate the player on the team given.
    getteam:
        usage: /getteam
        decription: Get the team that is being authenticated.
    wlteam:
        usage: /wlteam add/remove <team>
        description: Add or remove a team to the whitelist.
    blacklist:
        usage: /blacklist add/remove <team>
        description: Add or remove a team from the blacklist.